services:
  impressoras:
    build: .
    image: impressoras:latest
    container_name: impressoras
    ports:
      - "8000:80"
    depends_on:
      - mariadb
    networks:
      - impressoras-network
    volumes:
      - ./:/var/www/html
    environment:
      HOME: /tmp
    user: "${UID:-1000}:${GID:-1000}"

  mariadb:
    image: mariadb:11
    container_name: impressoras_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: impressoras
      MYSQL_USER: impressoras
      MYSQL_PASSWORD: impressoras
      MYSQL_ROOT_PASSWORD: impressoras
    networks:
      - impressoras-network

  selenium:
    image: selenium/standalone-chrome
    container_name: impressoras_selenium
    ports:
      - "7900:7900" # VNC (pra ver o browser rodando)
    networks:
      - impressoras-network
    shm_size: 2gb

  cups:
    image: olbat/cupsd:latest
    container_name: impressoras_cups
    ports:
      - '8631:631'
    environment:
      - CUPS_ADMIN=admin
      - CUPS_PASSWORD=senha
    networks:
      - impressoras-network

networks:
  impressoras-network: